version: 1.0.{build}

image: Visual Studio 2017

platform:
  - x64

configuration:
  - Debug
  - Release

environment:
  BUILD_PATH: $(platform)\$(configuration)
  matrix:
    - arch: x64
      compiler: msvc2017
      PREMAKE_GENERATOR: vs2017
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

before_build:
  - cmd: "configure-%PREMAKE_GENERATOR%.bat"

build_script:
  - cmd: msbuild "build-%PREMAKE_GENERATOR%/bifrost.sln" /p:Configuration="%CONFIGURATION%" /m /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

test_script:
  - ps: |
      Foreach($i in "bifrost-shared") {
        Start-Process -FilePath "build-$($env:PREMAKE_GENERATOR)/bin/$($env:CONFIGURATION)/test-$i.exe" -ArgumentList "--gtest_output=xml:$i-gtest-result.xml" -Wait -NoNewWindow;
        dir;
        echo ".\$1-gtest-result.xml";
        If (Test-Path .\$1-gtest-result.xml) {
          echo ".\$1-gtest-result.xml";
          (New-Object System.Net.WebClient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\$1-gtest-result.xml))
        }
      }
