version: 1.0.{build}

image: 
    - Visual Studio 2019

platform:
  - x64

configuration:
  - Debug
  - Release

environment:
  BUILD_PATH: $(platform)\$(configuration)
  matrix:
    - arch: x64
      compiler: msvc2019
      PREMAKE_GENERATOR: vs2019
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      

before_build:
  - cmd: dotnet --version
  - cmd: "configure-%PREMAKE_GENERATOR%.bat"

build_script:
  - cmd: nuget restore "build-%PREMAKE_GENERATOR%/bifrost.sln"
  - cmd: msbuild "build-%PREMAKE_GENERATOR%/bifrost.sln" /p:Configuration="%CONFIGURATION%" /m /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

test_script:
  # Run C++ unit tests
  - ps: |
        $exitCode = 0;
        Foreach($i in "bifrost-core","bifrost-api") {
            $proc = Start-Process -FilePath "build-$($env:PREMAKE_GENERATOR)/bin/$($env:CONFIGURATION)/test-$i.exe" -ArgumentList "--gtest_output=xml:$i-gtest-result.xml" `
                                  -Wait -NoNewWindow -RedirectStandardOutput ".\$i-output.txt" -RedirectStandardError ".\$i-err.txt";
            Get-Content -Path ".\$i-output.txt";
            Get-Content -Path ".\$i-err.txt";
            If($proc.ExitCode -ne 0) {
              $exitCode = 1;
            }
            If (Test-Path .\$i-gtest-result.xml) {
                (New-Object System.Net.WebClient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\$i-gtest-result.xml))
            }
        }
        if($exitCode -ne 0) {
            exit $exitCode;
        }
