version: 1.0.{build}

image: 
    - Visual Studio 2019

platform:
  - x64

configuration:
  - Debug
  - Release

environment:
  BUILD_PATH: $(platform)\$(configuration)
  matrix:
    - arch: x64
      compiler: msvc2019
      PREMAKE_GENERATOR: vs2019
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      

before_build:
  - cmd: dotnet --version
  - cmd: "configure-%PREMAKE_GENERATOR%.bat"

build_script:
  - cmd: nuget restore "build-%PREMAKE_GENERATOR%/bifrost.sln"
  - cmd: msbuild "build-%PREMAKE_GENERATOR%/bifrost.sln" /p:Configuration="%CONFIGURATION%" /m /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

test_script:
  # Run C++ unit tests
  - ps: .\ci\unit_tests.ps1 "build-$($env:PREMAKE_GENERATOR)/bin/$($env:CONFIGURATION)"