#pragma region Plugin Namespace

#ifndef BIFROST_NAMESPACE
#define BIFROST_NAMESPACE bifrost
#endif

#define BIFROST_NAMESPACE_BEGIN namespace BIFROST_NAMESPACE {
#define BIFROST_NAMESPACE_END }

#define BIFROST_NAMESPACE_CONCAT_IMPL(x, y) x##y
#define BIFROST_NAMESPACE_CONCAT(x, y) BIFROST_NAMESPACE_CONCAT_IMPL(x, y)

#define BIFROST_NAMESPACE_UNQUALIFIED(x) BIFROST_NAMESPACE_CONCAT(::, BIFROST_NAMESPACE_CONCAT(BIFROST_NAMESPACE, BIFROST_NAMESPACE_CONCAT(::, x)))

#pragma endregion
